### PR TITLE
Feature/alternative api

### PR DESCRIPTION
**Pull request by brianmcgee**
Basic implementation of RxCache with some tests

### CODE REVIEW

**Comment by brianmcgee** [comment]
@joselufo @aldoborrero merge this when you want. We should discuss the implementation.

**Comment by brianmcgee** [comment]
@aldoborrero the NoOp is meant for people who don't use versioned objects. The cache is version aware always. We can make it's use internal, i.e. if they don't set a version mapper we set the NoOp version mapper. But it's an essential piece.

**Comment by aldoborrero** [comment]
@joselufo I'll add the OK to this pull request, as long as you have time to check it and agree, do the pull merge!

**Comment by joselufo** [comment]
@brianmcgee all OK for me as well. I have some suggestion but we can discuss it on Monday. 

I will merge and close the pull request, please open new pull requests more specific to be more clear because the alternative api is very advanced.

**Comment by joselufo** [comment]
@brianmcgee Please delete the branch when you can.

**Pull request merged**
